server {
    listen 80;
    listen [::]:80;
    server_name chengguo.youpulab.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/youpulab;
        default_type "text/plain";
    }

    location / {
        return 404;
    }
}
